config/routes.rb
Rails.application.routes.draw do
  get 'relationships/followings'
  get 'relationships/followers'
  devise_for :users
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  resources :users, except: [:new, :create, :destroy] do
    resource :relationships, only: [:create, :destroy]
    get 'relationships/followings' => 'relationships#followings', as: 'followings'
    get 'relationships/followers' => 'relationships#followers', as: 'followers'
  end
  resources :books, except: [:new] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites,dependent: :destroy

   def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
   end

  validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}
end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :comment, presence: true

end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  attachment :profile_image
  has_many :book_comments
  has_many :favorites, dependent: :destroy

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed

  validates :name, length: {maximum: 20, minimum: 2}, uniqueness: true
  validates :introduction, length: {maximum: 50}

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    @comment = current_user.book_comments.new(book_comment_params)
    @comment.book_id = @book.id
    @comment.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    comment = @book.book_comments.find(params[:id])
    comment.destroy
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!

  def index
    @books = Book.all
    @user = current_user
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
    @user = @book.user
    @comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
       redirect_to book_path(@book.id),
       notice: "You have created book successfully"
    else
      @books = Book.all
      @user = current_user
      render 'index'
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
       redirect_to books_path,
       notice: "You have updated book successfully."
    else
      render 'edit'
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!

  def create
    @book = Book.find(params[:book_id])
    favorite = @book.favorites.new(user_id: current_user.id)
    favorite.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = @book.favorites.find_by(user_id: current_user.id)
    favorite.destroy
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!

  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end

  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer
  end

  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
       redirect_to users_path,
       notice: "You have updated user successfully."
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/_index.html.erb
<% @book.book_comments.each do |comment| %>
 <tr>
  <td>
    <%= link_to user_path(comment.user) do %>
      <%= attachment_image_tag comment.user, :profile_image, fallback: 'no_image.jpg', size: '50x50' %><br>
      <%= comment.user.name %>
    <% end %>
  </td>
  <td><%= comment.comment %></td>
  <% if comment.user == current_user %>
    <td><%= link_to "Destroy", book_book_comment_path(comment.book, comment),method: :delete, remote: true, class: "btn btn-danger" %></td>
  <% end %>
 </tr>
<% end %>

app/views/book_comments/create.js.erb
$("#book_<%= @book.id %> .comments_count").html("コメント数：<%= @book.book_comments.count  %>");
$(".book_comments").html("<%= j(render 'book_comments/index', book: @book) %>");
$("#book_comment_comment").val("");

app/views/book_comments/destroy.js.erb
$("#book_<%= @book.id %> .comments_count").html("コメント数：<%= @book.book_comments.count  %>");
$(".book_comments").html("<%= j(render 'book_comments/index', book: @book) %>");
$("#book_comment_comment").val("");

app/views/books/_form.html.erb
      <h2 class="mt-3">New book</h2>
      <%= form_with model: book, url: books_path, local:true do |f| %>
        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, class: "form-control book_title" %>
        </div>
        <div class="form-group">
          <%= f.label :opinion %>
          <%= f.text_area :body, class: "form-control book_body" %>
        </div>
        <div class="form-group">
          <%= f.submit  class: "btn btn-success" %>
        </div>
      <% end %>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
  		<%= render 'layouts/error', model: @book %>
    	<%= form_with model: @book, local:true do |f| %>
  		  <div class="form-group">
          <%= f.label :Title %>
          <%= f.text_field :title, class: "form-control book_title" %>
        </div>
        <div class="form-group">
          <%= f.label :Opinion %>
          <%= f.text_area :body, class: "form-control book_body" %>
        </div>
        <div class="form-group">
          <%= f.submit class: "btn btn-success" %>
        </div>
      <% end %>
  		<%= link_to "Show", book_path(@book.id) %> |
  		<%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <%= render 'layouts/error', model: @book %>
  <div class="row">
   <div class="col-md-3">
      <%= render 'users/form.profile', user: @user %>
      <%= render 'form', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th></th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
              <tr id="book_<%= book.id %>">
                <td>
                  <%= link_to user_path(book.id) do %>
                    <%= attachment_image_tag book.user, :profile_image, fallback: 'no_image.jpg', size: '50x50' %>
                  <% end %>
                </td>
                <td>
                  <%= link_to book_path(book.id) do %>
                    <%= book.title %>
                  <% end %>
                  </td>
                <td><%= book.body %></td>
                <td class="favorite-btn"><%= render 'favorites/favorite-button', book: book %></td>
                <td class="comments_count">
                  コメント数：<%= book.book_comments.count %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <%= render 'layouts/error', model: @book %>
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/form.profile', user: @user %>
      <%= render 'form', book: @book_new %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
          <tbody>
              <tr id="book_<%= @book.id %>">
                <td>
                  <%= link_to user_path(@book.id) do %>
                    <%= attachment_image_tag @book.user, :profile_image, fallback: 'no_image.jpg', size: '50x50' %><br>
                    <%= @book.user.name %>
                  <% end %>
                </td>
                <td>
                  <%= link_to book_path(@book.id) do %>
                    <%= @book.title %>
                  <% end %>
                </td>
                <td><%= @book.body %></td>
                <td class="favorite-btn"><%= render 'favorites/favorite-button', book: @book %></td>
                <td class="comments_count">
                  コメント数：<%= @book.book_comments.count %>
                </td>
                <% if @book.user == current_user %>
                  <td><%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-success" %></td>
                  <td><%= link_to "Destroy", book_path(@book.id), method: :delete, class: "btn btn-danger", data: {confirm: "本当に消しますか？"} %></td>
                <% end %>
              </tr>
          </tbody>
        </table>
        <table class="book_comments">
          <%= render 'book_comments/index', book: @book %>
        </table>
        <%= form_with model:[@book,@comment] do |f| %>
          <div>
            <%= f.text_area :comment, class: "control-form", size: "100x5" %>
          </div>
          <%= f.submit "送信" %>
        <% end %>
    </div>
  </div>
</div>

app/views/favorites/_favorite-button.html.erb
<% if book.favorited_by?(current_user) %>
  <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
    🖤<%= book.favorites.count %>
  <% end %>
<% else %>
  <%= link_to book_favorites_path(book), method: :post, remote: true do %>
    ♡<%= book.favorites.count %>
  <% end %>
<% end %>

app/views/favorites/create.js.erb
$("#book_<%= @book.id %> .favorite-btn").html("<%= j(render 'favorites/favorite-button', book: @book) %>");

app/views/favorites/destroy.js.erb
$("#book_<%= @book.id %> .favorite-btn").html("<%= j(render 'favorites/favorite-button', book: @book) %>");

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
        </div>
        <div class="row">
          <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign Up</a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_error.html.erb
<% if model.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(model.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2Review</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/"><span>Bookers</span></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <% if user_signed_in? %>
            <ul class="navbar-nav ml-auto">
              <li><%= link_to "Home", user_path(current_user), class: "fas fa-home nav-link text-light" %></li>
              <li><%= link_to "Users", users_path, class: "fas fa-users nav-link text-light" %></li>
              <li><%= link_to "Books", books_path, class: "fas fa-book-open nav-link text-light" %></li>
              <li><%= link_to "log out", destroy_user_session_path, class: "fas fa-sign-out-alt nav-link text-light" %></li>
            </ul>
            <% else %>
            <ul class="navbar-nav ml-auto">
              <li><%= link_to "Home", root_path, class: "fas fa-home nav-link text-light" %></li>
              <li><%= link_to "About", home_about_path, class: "fas fa-link nav-link text-light" %></li>
              <li><%= link_to "sign up", new_user_registration_path, class: "fas fa-user-plus nav-link text-light" %></li>
              <li><%= link_to "log in", new_user_session_path, class: "fas fa-sign-in-alt nav-link text-light" %></li>
            </ul>
            <% end %>
          </div>
        </div>
      </nav>
    </header>
    <p><%= notice %></p>
    <%= yield %>
    <footer>
      <div class="container mt-5">
    	  <div class="row">
        	<div class="mx-auto">
    	    	<p>CopyRight Infratop.inc</p>
    	    </div>
        </div>
      </div>
    </footer>
  </body>

</html>

app/views/relationships/_follow.html.erb
<% if current_user.following?(user) %>
  <%= link_to "フォローを外す", user_relationships_path(user.id), method: :delete, class: "btn btn-info" %>
<% else %>
  <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-secondary " %>
<% end %>

app/views/relationships/create.js.erb
$(".follow").html("<%= j(render 'relationships/follow', user: @user) %>");

app/views/relationships/destroy.js.erb
$(".follow").html("<%= j(render 'relationships/follow', user: @user) %>");

app/views/relationships/followers.html.erb
<h2>Follower Users</h2>
<% if @users.exists? %>
  <table class="table">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th></th>
              <th></th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td><%= attachment_image_tag user, :profile_image, fallback: 'no_image.jpg', size: '50x50' %></td>
                <td><%= user.name %></td>
                <td>フォロー数：<%= user.followings.count %></td>
                <td>フォロワー数：<%= user.followers.count %></td>
                <% if current_user != user %>
                  <td class="follow"><%= render 'relationships/follow', user: user %></td>
                <% end %>
                <td><%= link_to "Show", user_path(user.id) %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/relationships/followings.html.erb
<h2>Follow Users</h2>
<% if @users.exists? %>
  <table class="table">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th></th>
              <th></th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td><%= attachment_image_tag user, :profile_image, fallback: 'no_image.jpg', size: '50x50' %></td>
                <td><%= user.name %></td>
                <td>フォロー数：<%= user.followings.count %></td>
                <td>フォロワー数：<%= user.followers.count %></td>
                <% if current_user != user %>
                  <td class="follow"><%= render 'relationships/follow', user: user %></td>
                <% end %>
                <td><%= link_to "Show", user_path(user.id) %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/users/_form.profile.html.erb
      <h2>User info</h2>
      <%= attachment_image_tag user, :profile_image, fallback: 'no_image.jpg', size: '150x150' %>
      <table class="table">
        <tbody>
          <tr>
	          <th>name</th>
	          <th><%= user.name %></th>
          </tr>
          <tr>
        	  <th>introduction</th>
        	  <th><%= user.introduction %></th>
          </tr>
          <tr>
            <th>follows</th>
            <th><%= link_to user.followings.count, user_followings_path(user) %></th>
          </tr>
          <tr>
            <th>followed</th>
            <th><%= link_to user.followers.count, user_followers_path(user) %></th>
          </tr>
        </tbody>
      </table>

      <div class="row">
        <% if user == current_user %>
          <%= link_to "", edit_user_path(current_user) ,class: "btn btn-outline-secondary btn-block fas fa-user-cog " %>
        <% else %>
          <div class="follow"><%= render 'relationships/follow', user: user %></div>
        <% end %>
      </div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <%= render 'layouts/error', model: @user %>
      <%= form_with model: @user, local:true do |f| %>
        <div class="form-group">
          <%= f.label :Name %>
          <%= f.text_field :name, class: "form-control name" %>
        </div>
        <div class="form-group">
          <%= f.label :Image %><br>
          <%= f.attachment_field :profile_image %>
        </div>
        <div class="form-group">
          <%= f.label :Introduction %>
          <%= f.text_area :introduction, class: "form-control introduction" %>
        </div>
        <div class="form-group">
          <%= f.submit "Update User", class: "btn btn-secondary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <%= render 'layouts/error', model: @book %>
  <div class="row">
    <div class="col-md-3">
      <%= render 'form.profile', user: @user %>
      <%= render 'books/form', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
        <table class="table">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th></th>
              <th></th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td><%= attachment_image_tag user, :profile_image, fallback: 'no_image.jpg', size: '50x50' %></td>
                <td><%= user.name %></td>
                <td>フォロー数：<%= user.followings.count %></td>
                <td>フォロワー数：<%= user.followers.count %></td>
                <% if current_user != user %>
                  <td class="follow"><%= render 'relationships/follow', user: user %></td>
                <% end %>
                <td><%= link_to "Show", user_path(user.id) %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <%= render 'layouts/error', model: @book %>
  <div class="row">
    <div class="col-md-3">
      <%= render 'form.profile', user: @user %>
      <%= render 'books/form', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.id) do %>
                <%= attachment_image_tag @user, :profile_image, fallback: 'no_image.jpg', size: '50x50' %></td>
              <% end %>
            <td>
              <%= link_to book_path(book.id) do %>
                <%= book.title %>
              <% end %>
            </td>
            <td><%= book.body %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>